apiVersion: batch/v1
kind: Job
metadata:
  name: hey
spec:
  completions: 3
  parallelism: 3
  backoffLimit: 1 # number of retries before throwing error
  #activeDeadlineSeconds: 10 # time to allow job to run
  ttlSecondsAfterFinished: 10
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: hey
        image: docker.io/r00tsh3llll/hey:latest
        imagePullPolicy: IfNotPresent
        command: ["/hey"]
        args: ["-n", "2000", "-c", "500", "https://www.sendo.vn"]


